### ISSUE TITLE
EF Migrations, Insert value for Text Data Type always has (Size=255)

### ISSUE THREAD

**Issue by Blastnsmash** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#50] opened 2017-03-01 18:53 UTC
I'm following a tutorial and using the .UseMySQL extension from Assembly SapientGuardian.EntityFrameworkCore.MySql, Version=7.1.19.0, Culture=neutral, PublicKeyToken=null

I am using the migrations from IdentityServer4 PersistedGrant Migration.

The Table Gets created properly with "text" data type but all inserts clip data column because of the insert statement below. Is there a way to override the insert statement?

info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (5ms) [Parameters=[@p0='?' (Size = 200), @p1='?' (Size = 50), @p2='?' (Size = 200), @p3='?', @p4='?' (Size = 255), @p5='?', @p6='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
      INSERT INTO `PersistedGrants` (`Key`, `Type`, `ClientId`, `CreationTime`, `Data`, `Expiration`, `SubjectId`)
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6);
dbug: MySQL.Data.Entity.MySQLRelationalConnection[6]
      Committing transaction.

**Comment by SapientGuardian** [comment] 2017-03-01 22:12
I believe this is a dupe of #47. See also: https://github.com/IdentityServer/IdentityServer4.EntityFramework/issues/54

**Comment by SapientGuardian** [comment] 2017-04-07 00:48
Closing as dupe

**Closed as completed by SapientGuardian** 2017-04-07 00:48 UTC
